#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=30
stage=0
stop_stage=7
perturb_speed=true


# We assume dl_dir (download dir) contains the following
# directories and files. If not, you need to apply aishell2 through
# their official website.
# https://www.aishelltech.com/aishell_2
#
#  - $dl_dir/aishell2
#
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#     - music
#     - noise
#     - speech

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "stage 0: Download data"

  # If you have pre-downloaded it to /path/to/aishell2,
  # you can create a symlink
  #
  #   ln -sfv /path/to/aishell2 $dl_dir/aishell2
  #
  # The directory structure is
  # aishell2/
  # |-- AISHELL-2
  # |   |-- iOS
  #         |-- data
  #             |-- wav
  #             |-- trans.txt
  #         |-- dev
  #             |-- wav
  #             |-- trans.txt
  #         |-- test
  #             |-- wav
  #             |-- trans.txt


  # If you have pre-downloaded it to /path/to/musan,
  # you can create a symlink
  #
  #   ln -sfv /path/to/musan $dl_dir/musan
  #
  if [ ! -d $dl_dir/musan ]; then
    lhotse download musan $dl_dir
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare aishell2 manifest"
  # We assume that you have downloaded and unzip the aishell2 corpus
  # to $dl_dir/aishell2
  if [ ! -f data/manifests/.aishell2_manifests.done ]; then
    mkdir -p data/manifests
    lhotse prepare aishell2 $dl_dir/aishell2 data/manifests -j $nj
    touch data/manifests/.aishell2_manifests.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Compute fbank for aishell2"
  if [ ! -f data/fbank/.aishell2.done ]; then
    mkdir -p data/fbank
    ./local/compute_fbank_aishell2.py --perturb-speed ${perturb_speed}
    touch data/fbank/.aishell2.done
  fi
fi
