#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

stage=-1
stop_stage=100
perturb_speed=true


# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/aishell4
#      You can find four directories:train_S, train_M, train_L and test.
#      You can download it from https://openslr.org/111/
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#     - music
#     - noise
#     - speech

dl_dir=$PWD/download
mkdir -p $dl_dir

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  # If you have pre-downloaded it to /path/to/aishell4,
  # you can create a symlink
  #
    ln -sfv /mgData1/yangb/data/download/aishell4 $dl_dir
  #
  if [ ! -d $dl_dir/aishell4/train_L ]; then
    lhotse download aishell4 $dl_dir/aishell4
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare aishell4 manifest"
  # We assume that you have downloaded the aishell4 corpus
  # to $dl_dir/aishell4
  if [ ! -f data/manifests/aishell4/.manifests.done ]; then
    mkdir -p data/manifests/aishell4
    lhotse prepare aishell4 $dl_dir/aishell4 data/manifests/aishell4 --normalize-text --save-mono
    touch data/manifests/aishell4/.manifests.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Compute fbank for aishell4"
  if [ ! -f data/fbank/.aishell4.done ]; then
    mkdir -p data/fbank
    ./local/compute_fbank_aishell4.py --perturb-speed ${perturb_speed}
    touch data/fbank/.aishell4.done
  fi
fi
