#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

stage=-1
stop_stage=100

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
#
#  - $dl_dir/alimeeting
#     This directory contains the following files downloaded from
#       https://openslr.org/62/
#
#     - Train_Ali_far.tar.gz
#     - Train_Ali_near.tar.gz
#     - Test_Ali.tar.gz
#     - Eval_Ali.tar.gz
#
#  - $dl_dir/musan
#      This directory contains the following directories downloaded from
#       http://www.openslr.org/17/
#
#     - music
#     - noise
#     - speech

dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Download data"

  if [ ! -d $dl_dir/alimeeting/Train_Ali_far ]; then
    lhotse download ali-meeting $dl_dir/alimeeting
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare alimeeting manifest"
  # We assume that you have downloaded the alimeeting corpus
  # to $dl_dir/alimeeting
  if [ ! -f data/manifests/alimeeting/.manifests.done ]; then
    mkdir -p data/manifests/alimeeting
    lhotse prepare ali-meeting $dl_dir/alimeeting data/manifests/alimeeting --mic sdm --normalize-text m2met --save-mono
    touch data/manifests/alimeeting/.manifests.done
  fi
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 2: Compute fbank for alimeeting"
  if [ ! -f data/fbank/.alimeeting.done ]; then
    mkdir -p data/fbank
    ./local/compute_fbank_alimeeting.py --perturb-speed True
    touch data/fbank/.alimeeting.done
  fi
fi
